export default [
  {
  login: "tonykaranja",
  id: 19831257,
  node_id: "MDQ6VXNlcjE5ODMxMjU3",
  avatar_url: "https://avatars3.githubusercontent.com/u/19831257?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tonykaranja",
  html_url: "https://github.com/tonykaranja",
  followers_url: "https://api.github.com/users/tonykaranja/followers",
  following_url: "https://api.github.com/users/tonykaranja/following{/other_user}",
  gists_url: "https://api.github.com/users/tonykaranja/gists{/gist_id}",
  starred_url: "https://api.github.com/users/tonykaranja/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/tonykaranja/subscriptions",
  organizations_url: "https://api.github.com/users/tonykaranja/orgs",
  repos_url: "https://api.github.com/users/tonykaranja/repos",
  events_url: "https://api.github.com/users/tonykaranja/events{/privacy}",
  received_events_url: "https://api.github.com/users/tonykaranja/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "pmbanda",
  id: 12620687,
  node_id: "MDQ6VXNlcjEyNjIwNjg3",
  avatar_url: "https://avatars0.githubusercontent.com/u/12620687?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/pmbanda",
  html_url: "https://github.com/pmbanda",
  followers_url: "https://api.github.com/users/pmbanda/followers",
  following_url: "https://api.github.com/users/pmbanda/following{/other_user}",
  gists_url: "https://api.github.com/users/pmbanda/gists{/gist_id}",
  starred_url: "https://api.github.com/users/pmbanda/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/pmbanda/subscriptions",
  organizations_url: "https://api.github.com/users/pmbanda/orgs",
  repos_url: "https://api.github.com/users/pmbanda/repos",
  events_url: "https://api.github.com/users/pmbanda/events{/privacy}",
  received_events_url: "https://api.github.com/users/pmbanda/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "brockers",
  id: 1927765,
  node_id: "MDQ6VXNlcjE5Mjc3NjU=",
  avatar_url: "https://avatars1.githubusercontent.com/u/1927765?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/brockers",
  html_url: "https://github.com/brockers",
  followers_url: "https://api.github.com/users/brockers/followers",
  following_url: "https://api.github.com/users/brockers/following{/other_user}",
  gists_url: "https://api.github.com/users/brockers/gists{/gist_id}",
  starred_url: "https://api.github.com/users/brockers/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/brockers/subscriptions",
  organizations_url: "https://api.github.com/users/brockers/orgs",
  repos_url: "https://api.github.com/users/brockers/repos",
  events_url: "https://api.github.com/users/brockers/events{/privacy}",
  received_events_url: "https://api.github.com/users/brockers/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "peterdamicone",
  id: 24554442,
  node_id: "MDQ6VXNlcjI0NTU0NDQy",
  avatar_url: "https://avatars1.githubusercontent.com/u/24554442?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/peterdamicone",
  html_url: "https://github.com/peterdamicone",
  followers_url: "https://api.github.com/users/peterdamicone/followers",
  following_url: "https://api.github.com/users/peterdamicone/following{/other_user}",
  gists_url: "https://api.github.com/users/peterdamicone/gists{/gist_id}",
  starred_url: "https://api.github.com/users/peterdamicone/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/peterdamicone/subscriptions",
  organizations_url: "https://api.github.com/users/peterdamicone/orgs",
  repos_url: "https://api.github.com/users/peterdamicone/repos",
  events_url: "https://api.github.com/users/peterdamicone/events{/privacy}",
  received_events_url: "https://api.github.com/users/peterdamicone/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "jcorendain",
  id: 51001012,
  node_id: "MDQ6VXNlcjUxMDAxMDEy",
  avatar_url: "https://avatars3.githubusercontent.com/u/51001012?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jcorendain",
  html_url: "https://github.com/jcorendain",
  followers_url: "https://api.github.com/users/jcorendain/followers",
  following_url: "https://api.github.com/users/jcorendain/following{/other_user}",
  gists_url: "https://api.github.com/users/jcorendain/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jcorendain/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jcorendain/subscriptions",
  organizations_url: "https://api.github.com/users/jcorendain/orgs",
  repos_url: "https://api.github.com/users/jcorendain/repos",
  events_url: "https://api.github.com/users/jcorendain/events{/privacy}",
  received_events_url: "https://api.github.com/users/jcorendain/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "june-brown",
  id: 46734908,
  node_id: "MDQ6VXNlcjQ2NzM0OTA4",
  avatar_url: "https://avatars0.githubusercontent.com/u/46734908?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/june-brown",
  html_url: "https://github.com/june-brown",
  followers_url: "https://api.github.com/users/june-brown/followers",
  following_url: "https://api.github.com/users/june-brown/following{/other_user}",
  gists_url: "https://api.github.com/users/june-brown/gists{/gist_id}",
  starred_url: "https://api.github.com/users/june-brown/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/june-brown/subscriptions",
  organizations_url: "https://api.github.com/users/june-brown/orgs",
  repos_url: "https://api.github.com/users/june-brown/repos",
  events_url: "https://api.github.com/users/june-brown/events{/privacy}",
  received_events_url: "https://api.github.com/users/june-brown/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "DanielOrendain",
  id: 50751117,
  node_id: "MDQ6VXNlcjUwNzUxMTE3",
  avatar_url: "https://avatars1.githubusercontent.com/u/50751117?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/DanielOrendain",
  html_url: "https://github.com/DanielOrendain",
  followers_url: "https://api.github.com/users/DanielOrendain/followers",
  following_url: "https://api.github.com/users/DanielOrendain/following{/other_user}",
  gists_url: "https://api.github.com/users/DanielOrendain/gists{/gist_id}",
  starred_url: "https://api.github.com/users/DanielOrendain/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/DanielOrendain/subscriptions",
  organizations_url: "https://api.github.com/users/DanielOrendain/orgs",
  repos_url: "https://api.github.com/users/DanielOrendain/repos",
  events_url: "https://api.github.com/users/DanielOrendain/events{/privacy}",
  received_events_url: "https://api.github.com/users/DanielOrendain/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "hamza-zoumhani",
  id: 46981219,
  node_id: "MDQ6VXNlcjQ2OTgxMjE5",
  avatar_url: "https://avatars1.githubusercontent.com/u/46981219?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/hamza-zoumhani",
  html_url: "https://github.com/hamza-zoumhani",
  followers_url: "https://api.github.com/users/hamza-zoumhani/followers",
  following_url: "https://api.github.com/users/hamza-zoumhani/following{/other_user}",
  gists_url: "https://api.github.com/users/hamza-zoumhani/gists{/gist_id}",
  starred_url: "https://api.github.com/users/hamza-zoumhani/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/hamza-zoumhani/subscriptions",
  organizations_url: "https://api.github.com/users/hamza-zoumhani/orgs",
  repos_url: "https://api.github.com/users/hamza-zoumhani/repos",
  events_url: "https://api.github.com/users/hamza-zoumhani/events{/privacy}",
  received_events_url: "https://api.github.com/users/hamza-zoumhani/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "mbogokennedy",
  id: 35559656,
  node_id: "MDQ6VXNlcjM1NTU5NjU2",
  avatar_url: "https://avatars3.githubusercontent.com/u/35559656?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/mbogokennedy",
  html_url: "https://github.com/mbogokennedy",
  followers_url: "https://api.github.com/users/mbogokennedy/followers",
  following_url: "https://api.github.com/users/mbogokennedy/following{/other_user}",
  gists_url: "https://api.github.com/users/mbogokennedy/gists{/gist_id}",
  starred_url: "https://api.github.com/users/mbogokennedy/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mbogokennedy/subscriptions",
  organizations_url: "https://api.github.com/users/mbogokennedy/orgs",
  repos_url: "https://api.github.com/users/mbogokennedy/repos",
  events_url: "https://api.github.com/users/mbogokennedy/events{/privacy}",
  received_events_url: "https://api.github.com/users/mbogokennedy/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "julesep3",
  id: 50899932,
  node_id: "MDQ6VXNlcjUwODk5OTMy",
  avatar_url: "https://avatars1.githubusercontent.com/u/50899932?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/julesep3",
  html_url: "https://github.com/julesep3",
  followers_url: "https://api.github.com/users/julesep3/followers",
  following_url: "https://api.github.com/users/julesep3/following{/other_user}",
  gists_url: "https://api.github.com/users/julesep3/gists{/gist_id}",
  starred_url: "https://api.github.com/users/julesep3/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/julesep3/subscriptions",
  organizations_url: "https://api.github.com/users/julesep3/orgs",
  repos_url: "https://api.github.com/users/julesep3/repos",
  events_url: "https://api.github.com/users/julesep3/events{/privacy}",
  received_events_url: "https://api.github.com/users/julesep3/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "samuel374",
  id: 69720352,
  node_id: "MDQ6VXNlcjY5NzIwMzUy",
  avatar_url: "https://avatars0.githubusercontent.com/u/69720352?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/samuel374",
  html_url: "https://github.com/samuel374",
  followers_url: "https://api.github.com/users/samuel374/followers",
  following_url: "https://api.github.com/users/samuel374/following{/other_user}",
  gists_url: "https://api.github.com/users/samuel374/gists{/gist_id}",
  starred_url: "https://api.github.com/users/samuel374/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/samuel374/subscriptions",
  organizations_url: "https://api.github.com/users/samuel374/orgs",
  repos_url: "https://api.github.com/users/samuel374/repos",
  events_url: "https://api.github.com/users/samuel374/events{/privacy}",
  received_events_url: "https://api.github.com/users/samuel374/received_events",
  type: "User",
  site_admin: false
  }
  ]