export default {
  login: "johnmwaura08",
  id: 51472368,
  node_id: "MDQ6VXNlcjUxNDcyMzY4",
  avatar_url: "https://avatars3.githubusercontent.com/u/51472368?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/johnmwaura08",
  html_url: "https://github.com/johnmwaura08",
  followers_url: "https://api.github.com/users/johnmwaura08/followers",
  following_url: "https://api.github.com/users/johnmwaura08/following{/other_user}",
  gists_url: "https://api.github.com/users/johnmwaura08/gists{/gist_id}",
  starred_url: "https://api.github.com/users/johnmwaura08/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/johnmwaura08/subscriptions",
  organizations_url: "https://api.github.com/users/johnmwaura08/orgs",
  repos_url: "https://api.github.com/users/johnmwaura08/repos",
  events_url: "https://api.github.com/users/johnmwaura08/events{/privacy}",
  received_events_url: "https://api.github.com/users/johnmwaura08/received_events",
  type: "User",
  site_admin: false,
  name: "John Mwaura",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Full-stack Developer. Contact for inquiries. ",
  twitter_username: null,
  public_repos: 42,
  public_gists: 0,
  followers: 11,
  following: 22,
  created_at: "2019-06-07T06:11:09Z",
  updated_at: "2020-10-06T05:35:36Z"
  }